### ISSUE TITLE
coverage.dat文件为空

### ISSUE THREAD

**Issue by jikechao** [panzhongxian/leetcode-cpp#2]
您好，根据你的readme，我试着复现coverage报告，结果发现生成的coverage.dat是一个空文件。请问可能的原因是什么呢，谢谢

**Comment by panzhongxian** [comment]
@jikechao  要根据 [覆盖率报告](https://github.com/panzhongxian/leetcode-cpp#%E8%A6%86%E7%9B%96%E7%8E%87%E6%8A%A5%E5%91%8A) 这一小节中使用 docker 进行覆盖率的生成哈。

看到你提的 Issue 之后，我又重新试了一下，发现之前的 benchmark 已经去掉了 master 分支，改成了 main 分支，所以对应的 WORKSPACE 需要修改，我已经在[最新的commit](https://github.com/panzhongxian/leetcode-cpp/commit/6eb5659262cca98f2dbb00d639ff4cd41c6d30aa)中做了修改，并且能生成组以后的覆盖率报告。

coverage.dat 是中间过程的产物，如果用 docker，项目目录下是不会产生这个文件的。你可以再试试

**Comment by anonymousWork000** [comment]
感谢您的回复。想请教您另外一个问题：bazel coverage 似乎每次都会编译一遍程序，是否存在命令/参数使得bazel只收集覆盖而不重新编译项目呢？期待您的解答，谢谢！

**Comment by jikechao** [comment]
谢谢您的回复！我想再请教您一个新的问题：bazel coverage 命令似乎每次都会重新编译一遍项目。是否存在命令/参数使得bazel可以收集到覆盖信息而不需要重新编译项目。期待您的回复！谢谢您。

**Comment by panzhongxian** [comment]
@jikechao 可以的，其实不是 `bazel coverage` 的问题，而是 Docker + Bazel 的原因。

[Bazel 的文档](https://docs.bazel.build/versions/master/output_directories.html#current-layout)中有介绍，Bazel 的 cache 默认位置是 `~/.cache/bazel`，里边有 bazel-bin、bazel-out等目录。

通过 `ls` 也可以看到，这 4 个链接实际是链到了镜像的内部地址，退出后就失效了。

![image](https://user-images.githubusercontent.com/11887422/120794853-58633000-c56b-11eb-9f83-22c162e7a6c2.png)

**如果通过 `docker` 的 `-v` 选项将其映射到宿主 机上解决上述问题**：

```bash
docker run -v $PWD:/leetcode-cpp -v /data/docker_cache:/root/.cache/bazel -t -i ubuntu:18.04 /bin/sh -c "cd leetcode-cpp && tools/coverage.sh"
```
就不要每次都重新编译项目了，可以看到再次编译很快：

![image](https://user-images.githubusercontent.com/11887422/120801854-4cc83700-c574-11eb-8b0e-3e4354b8315a.png)


**欢迎关注我的公众号 “老白码农在奋斗” 进行交流~**

**Comment by jikechao** [comment]
谢谢您认真的回复。已关注，希望以后有机会和您继续交流学习。

**Comment by panzhongxian** [comment]
已经将 coverage 和 build 的输出固定指向 `--output_base=/tmp/bazel_output`，如果需要映射，则使用 `-v /data/docker_cache:/tmp/bazel_output` 进行映射

**Comment by xiaqunfeng** [comment]
我在mac上也遇到了同样的问题，生成覆盖率时报错：
genhtml: ERROR: no valid records found in tracefile bazel-out//darwin-fastbuild/testlogs/0002_add-two-numbers_test/coverage.dat
请问是只能在你的docker下生成覆盖率么？

**Comment by panzhongxian** [comment]
@xiaqunfeng Hi, 我修了一个 tools/coverage.sh，将coverage命令做了如下修改，Mac上可以看到dat文件，你可以试试：

```
bazel --output_base=/tmp/bazel_output coverage --combined_report=lcov //:all --javabase=@bazel_tools//tools/jdk:remote_jdk11
```

**Comment by xiaqunfeng** [comment]
> @xiaqunfeng Hi, 我修了一个 tools/coverage.sh，将coverage命令做了如下修改，Mac上可以看到dat文件，你可以试试：
> 
> ```
> bazel --output_base=/tmp/bazel_output coverage --combined_report=lcov //:all --javabase=@bazel_tools//tools/jdk:remote_jdk11
> ```

刚试了一下，还是一样的：
INFO: Elapsed time: 50.617s, Critical Path: 21.74s
INFO: 127 processes: 40 internal, 85 darwin-sandbox, 2 worker.
INFO: Build completed successfully, 127 total actions
//:0001_two-sum_test                                                     PASSED in 1.5s
//:0002_add-two-numbers_test                                             PASSED in 1.5s

Executed 2 out of 2 tests: 2 tests pass.
INFO: Build completed successfully, 127 total actions
Reading data file bazel-out//darwin-fastbuild/testlogs/0002_add-two-numbers_test/coverage.dat
genhtml: ERROR: no valid records found in tracefile bazel-out//darwin-fastbuild/testlogs/0002_add-two-numbers_test/coverage.dat

coverage.dat 文件大小是0
▶ ll bazel-out//darwin-fastbuild/testlogs/0002_add-two-numbers_test/coverage.dat
-r-xr-xr-x 1 xiaqunfeng wheel 0 Jun 29 10:59 bazel-out//darwin-fastbuild/testlogs/0002_add-two-numbers_test/coverage.dat

▶ ll bazel-out/darwin-fastbuild/testlogs/0001_two-sum_test/coverage.dat
-r-xr-xr-x 1 xiaqunfeng wheel 0 Jun 29 10:59 bazel-out/darwin-fastbuild/testlogs/0001_two-sum_test/coverage.dat

**Comment by panzhongxian** [comment]
@xiaqunfeng 那就用docker吧 ;-)
